name: build-apk
env:
  ANDROID_SDK_TOOLS: "8092744"
  ANDROID_CMAKE: "3.10.2.4988404"
on:
  push:
    branches:
      - master
    paths:
      - apps/**
jobs:
  build-apk-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Where is JAVA
        run: whereis javac
      - name: Where is JAVA
        run: readlink -f $(which java) 
      - name: Create Android HOME
        run: mkdir android-cli
      - name: Install Android sdkmanager
        run: |
          wget --quiet --output-document=android-sdk.zip https://dl.google.com/android/repository/commandlinetools-linux-{ANDROID_SDK_TOOLS}.zip
          sudo unzip -d android-cli android-sdk.zip > /dev/null
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm i -g @bubblewrap/cli
      - run: echo '{"jdkPath":"./open-jdk","androidSdkPath":"./android-cli"}' > ${USER_HOME}/.bubblewrap/config.json
      - run: bubblewrap init --manifest=https://gcode.com.au/apps/37790665-gps/manifest.json
