name: build-apk
env:
  ANDROID_SDK_TOOLS: "8092744"
  ANDROID_CMAKE: "3.10.2.4988404"
on:
  push:
    branches:
      - master
    paths:
      - apps/**
jobs:
  build-apk-job:
    timeout-minutes: 6
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Where is JAVA
        run: whereis javac
      - name: Where is JAVA
        run: readlink -f $(which java)
      - name: List Android
        run: ls -latr /usr/local/lib/android/sdk
      - name: List JAVA
        run: ls -latr $JAVA_HOME
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm i -g @bubblewrap/cli
      - run: mkdir ~/tools && cd ~/tools && npm init -y && npm i bw_manifest_url
      - run: mkdir ~/.bubblewrap
      - run: echo '{"jdkPath":"'$JAVA_HOME'","androidSdkPath":"/usr/local/lib/android/sdk"}' > ~/.bubblewrap/config.json
      - run: node ~/tools/node_modules/bw_manifest_url/init.js https://gcode.com.au/apps/37790665-gps/manifest.json
      - run: bubblewrap build
