name: build-apk
env:
  ANDROID_SDK_TOOLS: "8092744"
  ANDROID_CMAKE: "3.10.2.4988404"
on:
  push:
    branches:
      - master
    paths:
      - apps/**
      - '!**/ios/**'
      - '!**/apk/**'
      - '!apps/gcode_manifests.json'
concurrency:
  group: Android ${{ github.event.head_commit.message }}
  cancel-in-progress: true
jobs:
  build-apk-job:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get details from manifest
        run: |
          echo ${{ github.event.head_commit.message }}
          APP_NAME="${{ github.event.head_commit.message }}"
          APP_NAME=${APP_NAME:7}
          echo "[$APP_NAME]"
          echo "[$APP_NAME]"
          SHORT_NAME=`grep '"short_name"' ./apps/$APP_NAME/manifest.json | sed -r 's/^[^:]*:.*"(.*)".*$/\1/'`
          THEME_COLOR=`grep '"theme_color"' ./apps/$APP_NAME/manifest.json | sed -r 's/^[^:]*:.*"(.*)".*$/\1/'`
          BACKGROUND_COLOR=`grep '"background_color"' ./apps/$APP_NAME/manifest.json | sed -r 's/^[^:]*:.*"(.*)".*$/\1/'`
          SHORT_NAME_NOSP=`echo "$SHORT_NAME" | sed 's/ //g'`
          echo "APP_NAME=$(echo $APP_NAME)" >> $GITHUB_ENV
          APP_VERSION=`grep '"version"' ./apps/$APP_NAME/manifest.json | sed -r 's/^[^:]*:.*"(.*)".*$/\1/'`
          APP_MAIN_VERSION=${APP_VERSION%.*}
          APP_SUB_VERSION=${APP_VERSION##*.}
          echo "APP_VERSION=$(echo $APP_VERSION)" >> $GITHUB_ENV
          echo "APP_MAIN_VERSION=$(echo $APP_MAIN_VERSION)" >> $GITHUB_ENV
          echo "APP_SUB_VERSION=$(echo $APP_SUB_VERSION)" >> $GITHUB_ENV
      - name: setup node
        uses: actions/setup-node@v3.3.0
        with:
          node-version: '>=16.0.0'
      - name: pwaBuilder build APK
        run: | 
          echo "APP_NAME = $APP_NAME"
          node -v
          npm install node-fetch
          mkdir build 
          cd build
          node ../modules/pwabuilder/buildAPK.mjs
          unzip -q pwa.zip
          ls
      - name: move to apps/apk dir # Move the generated files into output folder
        run: |
          MANIFEST_URL="https://gcode.com.au/apps/$APP_NAME/manifest.json"
          echo "$MANIFEST_URL"
          echo "APP_NAME $APP_NAME"
          mkdir -p apps/$APP_NAME/apk
          rm -f apps/$APP_NAME/apk/*
          cp -rf ./build/*.apk ./apps/$APP_NAME/apk/
          cp -rf ./build/*.aab ./apps/$APP_NAME/apk/
          ls -latr ./apps/$APP_NAME/apk/     
          git config --local user.email "craig@gormantec.com"
          git config --local user.name "gormantec"
          git add ./apps/$APP_NAME/apk
          git commit -m "Add changes"
          git pull --rebase
          git push
